name: "My 1st workflow"

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        working-directory: "projects/steadyReadyGo/with_ts"
        run: |
          npm ci --silent
          npm run build
      - name: Deploy
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: projects/steadyReadyGo/with_ts/build
