name: "My 1st workflow"

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Compile
        run: tsc
  
